-- ============================================================
-- PROJETO INTEGRADOR
-- SISTEMA DE PROGRAMAÇÃO DE PRODUÇÃO E MONTAGEM DE CARGAS
-- Banco de Dados: PostgreSQL / Supabase
-- ============================================================


-- ============================================================
-- 1. TABELA CARGA
-- ============================================================

CREATE TABLE IF NOT EXISTS CARGA (
    id_carga INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_montagem DATE NOT NULL,
    data_entrega_prevista DATE NOT NULL,
    cidade VARCHAR(100) NOT NULL,
    peso_total DECIMAL(10,2) NOT NULL DEFAULT 0,
    capacidade_veiculo DECIMAL(10,2) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'Planejada',

    CONSTRAINT chk_carga_peso
        CHECK (peso_total >= 0),

    CONSTRAINT chk_carga_capacidade
        CHECK (capacidade_veiculo > 0)
);


-- ============================================================
-- 2. TABELA MAQUINA
-- ============================================================

CREATE TABLE IF NOT EXISTS MAQUINA (
    id_maquina INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_maquina VARCHAR(100) NOT NULL,
    tipo_maquina VARCHAR(50) NOT NULL,
    capacidade_horas DECIMAL(10,2) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'Disponível',

    CONSTRAINT chk_maquina_capacidade
        CHECK (capacidade_horas > 0)
);


-- ============================================================
-- 3. TABELA COR
-- ============================================================

CREATE TABLE IF NOT EXISTS COR (
    id_cor INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_cor VARCHAR(50) NOT NULL,
    grupo_cor VARCHAR(50) NOT NULL,
    ordem_sequenciamento INTEGER NOT NULL,
    tipo_lavagem VARCHAR(50) NOT NULL,

    CONSTRAINT uq_cor_nome
        UNIQUE (nome_cor),

    CONSTRAINT chk_cor_ordem
        CHECK (ordem_sequenciamento > 0)
);


-- ============================================================
-- 4. TABELA USUARIO
-- ============================================================

CREATE TABLE IF NOT EXISTS USUARIO (
    id_usuario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    login VARCHAR(50) NOT NULL,
    senha VARCHAR(255) NOT NULL,
    perfil VARCHAR(30) NOT NULL,

    CONSTRAINT uq_usuario_login
        UNIQUE (login),

    CONSTRAINT chk_usuario_perfil
        CHECK (perfil IN ('PCP/Gestor', 'Operador'))
);


-- ============================================================
-- 5. TABELA ORDEM_FABRICACAO
-- ============================================================

CREATE TABLE IF NOT EXISTS ORDEM_FABRICACAO (
    id_of INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_destino VARCHAR(100) NOT NULL,
    cidade VARCHAR(100) NOT NULL,
    data_entrega DATE NOT NULL,
    peso DECIMAL(10,2) NOT NULL,
    medida VARCHAR(50) NOT NULL,
    tipo_of VARCHAR(30) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'Pendente',
    id_carga INTEGER,

    CONSTRAINT chk_of_peso
        CHECK (peso > 0),

    CONSTRAINT chk_of_tipo
        CHECK (tipo_of IN ('Específica', 'Compartilhada')),

    CONSTRAINT fk_of_carga
        FOREIGN KEY (id_carga)
        REFERENCES CARGA(id_carga)
);


-- ============================================================
-- 6. TABELA PARADA_MAQUINA
-- ============================================================

CREATE TABLE IF NOT EXISTS PARADA_MAQUINA (
    id_parada INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_inicio TIMESTAMP NOT NULL,
    data_fim TIMESTAMP,
    motivo VARCHAR(100) NOT NULL,
    observacao TEXT,

    CONSTRAINT chk_parada_datas
        CHECK (data_fim IS NULL OR data_fim >= data_inicio)
);


-- ============================================================
-- 7. TABELA LOTE_PRODUCAO
-- ============================================================

CREATE TABLE IF NOT EXISTS LOTE_PRODUCAO (
    id_lote INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_lote VARCHAR(50) NOT NULL,
    quantidade INTEGER NOT NULL,
    data_inicio TIMESTAMP,
    data_fim TIMESTAMP,
    status VARCHAR(30) NOT NULL DEFAULT 'Aberto',

    CONSTRAINT uq_lote_numero
        UNIQUE (numero_lote),

    CONSTRAINT chk_lote_quantidade
        CHECK (quantidade > 0),

    CONSTRAINT chk_lote_datas
        CHECK (data_fim IS NULL OR data_inicio IS NULL OR data_fim >= data_inicio)
);


-- ============================================================
-- 8. TABELA MATERIA_PRIMA
-- ============================================================

CREATE TABLE IF NOT EXISTS MATERIA_PRIMA (
    id_material INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_material VARCHAR(100) NOT NULL,
    quantidade_estoque DECIMAL(10,2) NOT NULL DEFAULT 0,
    estoque_minimo DECIMAL(10,2) NOT NULL DEFAULT 0,
    unidade_medida VARCHAR(20) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'Normal',

    CONSTRAINT chk_material_estoque
        CHECK (quantidade_estoque >= 0),

    CONSTRAINT chk_material_minimo
        CHECK (estoque_minimo >= 0)
);


-- ============================================================
-- 9. TABELA CHECAGEM_QUALIDADE
-- ============================================================

CREATE TABLE IF NOT EXISTS CHECAGEM_QUALIDADE (
    id_checagem INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_checagem TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resultado VARCHAR(50) NOT NULL,
    observacao TEXT,
    id_parada INTEGER,

    CONSTRAINT fk_checagem_parada
        FOREIGN KEY (id_parada)
        REFERENCES PARADA_MAQUINA(id_parada)
);


-- ============================================================
-- 10. TABELA MOTIVO
-- ============================================================

CREATE TABLE IF NOT EXISTS MOTIVO (
    id_motivo INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao VARCHAR(150) NOT NULL,
    tipo VARCHAR(50) NOT NULL
);


-- ============================================================
-- 11. TABELA ALTERACAO_FILA
-- ============================================================

CREATE TABLE IF NOT EXISTS ALTERACAO_FILA (
    id_alteracao INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_alteracao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    justificativa TEXT NOT NULL,
    ordem_anterior INTEGER NOT NULL,
    nova_ordem INTEGER NOT NULL,
    id_parada INTEGER,
    id_material INTEGER,
    id_motivo INTEGER,

    CONSTRAINT chk_alteracao_ordem_anterior
        CHECK (ordem_anterior > 0),

    CONSTRAINT chk_alteracao_nova_ordem
        CHECK (nova_ordem > 0),

    CONSTRAINT fk_alteracao_parada
        FOREIGN KEY (id_parada)
        REFERENCES PARADA_MAQUINA(id_parada),

    CONSTRAINT fk_alteracao_material
        FOREIGN KEY (id_material)
        REFERENCES MATERIA_PRIMA(id_material),

    CONSTRAINT fk_alteracao_motivo
        FOREIGN KEY (id_motivo)
        REFERENCES MOTIVO(id_motivo)
);


-- ============================================================
-- 12. TABELA OF_MAQUINA
-- ============================================================

CREATE TABLE IF NOT EXISTS OF_MAQUINA (
    id_of INTEGER NOT NULL,
    id_maquina INTEGER NOT NULL,
    ordem_na_fila INTEGER NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'Aguardando',

    PRIMARY KEY (id_of, id_maquina),

    CONSTRAINT chk_of_maquina_ordem
        CHECK (ordem_na_fila > 0),

    CONSTRAINT fk_of_maquina_of
        FOREIGN KEY (id_of)
        REFERENCES ORDEM_FABRICACAO(id_of)
        ON DELETE CASCADE,

    CONSTRAINT fk_of_maquina_maquina
        FOREIGN KEY (id_maquina)
        REFERENCES MAQUINA(id_maquina)
);


-- ============================================================
-- 13. TABELA OF_COR
-- ============================================================

CREATE TABLE IF NOT EXISTS OF_COR (
    id_of INTEGER NOT NULL,
    id_cor INTEGER NOT NULL,

    PRIMARY KEY (id_of, id_cor),

    CONSTRAINT fk_of_cor_of
        FOREIGN KEY (id_of)
        REFERENCES ORDEM_FABRICACAO(id_of)
        ON DELETE CASCADE,

    CONSTRAINT fk_of_cor_cor
        FOREIGN KEY (id_cor)
        REFERENCES COR(id_cor)
);


-- ============================================================
-- 14. TABELA OF_LOTE
-- ============================================================

CREATE TABLE IF NOT EXISTS OF_LOTE (
    id_of INTEGER NOT NULL,
    id_lote INTEGER NOT NULL,

    PRIMARY KEY (id_of, id_lote),

    CONSTRAINT fk_of_lote_of
        FOREIGN KEY (id_of)
        REFERENCES ORDEM_FABRICACAO(id_of)
        ON DELETE CASCADE,

    CONSTRAINT fk_of_lote_lote
        FOREIGN KEY (id_lote)
        REFERENCES LOTE_PRODUCAO(id_lote)
);


-- ============================================================
-- 15. TABELA LOTE_MATERIAL
-- ============================================================

CREATE TABLE IF NOT EXISTS LOTE_MATERIAL (
    id_lote INTEGER NOT NULL,
    id_material INTEGER NOT NULL,
    quantidade_utilizada DECIMAL(10,2) NOT NULL,

    PRIMARY KEY (id_lote, id_material),

    CONSTRAINT chk_lote_material_quantidade
        CHECK (quantidade_utilizada > 0),

    CONSTRAINT fk_lote_material_lote
        FOREIGN KEY (id_lote)
        REFERENCES LOTE_PRODUCAO(id_lote)
        ON DELETE CASCADE,

    CONSTRAINT fk_lote_material_material
        FOREIGN KEY (id_material)
        REFERENCES MATERIA_PRIMA(id_material)
);


-- ============================================================
-- 16. TABELA CARGA_USUARIO
-- ============================================================

CREATE TABLE IF NOT EXISTS CARGA_USUARIO (
    id_carga INTEGER NOT NULL,
    id_usuario INTEGER NOT NULL,

    PRIMARY KEY (id_carga, id_usuario),

    CONSTRAINT fk_carga_usuario_carga
        FOREIGN KEY (id_carga)
        REFERENCES CARGA(id_carga)
        ON DELETE CASCADE,

    CONSTRAINT fk_carga_usuario_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES USUARIO(id_usuario)
);


-- ============================================================
-- 17. TABELA USUARIO_CHECAGEM
-- ============================================================

CREATE TABLE IF NOT EXISTS USUARIO_CHECAGEM (
    id_usuario INTEGER NOT NULL,
    id_checagem INTEGER NOT NULL,

    PRIMARY KEY (id_usuario, id_checagem),

    CONSTRAINT fk_usuario_checagem_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES USUARIO(id_usuario)
        ON DELETE CASCADE,

    CONSTRAINT fk_usuario_checagem_checagem
        FOREIGN KEY (id_checagem)
        REFERENCES CHECAGEM_QUALIDADE(id_checagem)
        ON DELETE CASCADE
);


-- ============================================================
-- DADOS FICTÍCIOS PARA TESTE
-- ============================================================


-- MÁQUINAS

INSERT INTO MAQUINA
(nome_maquina, tipo_maquina, capacidade_horas, status)
VALUES
('Impressora 01', 'Impressão', 8.00, 'Disponível'),
('Impressora 02', 'Impressão', 8.00, 'Disponível'),
('Corte 01', 'Corte/Vinco', 8.00, 'Disponível'),
('Corte 02', 'Corte/Vinco', 8.00, 'Disponível'),
('Colagem 01', 'Colagem/Acabamento', 8.00, 'Disponível');


-- CORES

INSERT INTO COR
(nome_cor, grupo_cor, ordem_sequenciamento, tipo_lavagem)
VALUES
('Branco', 'Clara', 1, 'Limpeza simples'),
('Amarelo', 'Clara', 2, 'Limpeza simples'),
('Laranja', 'Intermediária', 3, 'Lavagem superficial'),
('Vermelho', 'Intermediária', 4, 'Lavagem superficial'),
('Azul', 'Escura', 5, 'Lavagem média'),
('Verde', 'Escura', 6, 'Lavagem média'),
('Violeta', 'Escura', 7, 'Lavagem média'),
('Marrom', 'Escura', 8, 'Lavagem rápida'),
('Preto', 'Preta', 9, 'Sem lavagem');


-- USUÁRIOS
-- As senhas abaixo são apenas valores fictícios para teste.

INSERT INTO USUARIO
(nome, login, senha, perfil)
VALUES
('Gestor PCP', 'gestor', '$2b$10$senha_ficticia_gestor', 'PCP/Gestor'),
('Operador Impressao', 'operador1', '$2b$10$senha_ficticia_operador', 'Operador'),
('Operador Corte', 'operador2', '$2b$10$senha_ficticia_operador', 'Operador');


-- CARGAS

INSERT INTO CARGA
(data_montagem, data_entrega_prevista, cidade, peso_total, capacidade_veiculo, status)
VALUES
('2026-09-12', '2026-09-14', 'Campinas', 1200.00, 2000.00, 'Aprovada'),
('2026-09-13', '2026-09-15', 'Sumaré', 850.00, 1500.00, 'Planejada'),
('2026-09-14', '2026-09-16', 'Limeira', 600.00, 1000.00, 'Planejada');


-- ORDENS DE FABRICAÇÃO

INSERT INTO ORDEM_FABRICACAO
(cliente_destino, cidade, data_entrega, peso, medida, tipo_of, status, id_carga)
VALUES
('Cliente A', 'Campinas', '2026-09-14', 400.00, '40x30 cm', 'Específica', 'Pendente', 1),
('Cliente B', 'Campinas', '2026-09-14', 350.00, '50x40 cm', 'Compartilhada', 'Pendente', 1),
('Cliente C', 'Sumaré', '2026-09-15', 300.00, '30x20 cm', 'Específica', 'Pendente', 2),
('Cliente D', 'Sumaré', '2026-09-15', 250.00, '40x30 cm', 'Compartilhada', 'Pendente', 2),
('Cliente E', 'Limeira', '2026-09-16', 200.00, '60x40 cm', 'Específica', 'Pendente', 3);


-- MATÉRIAS-PRIMAS

INSERT INTO MATERIA_PRIMA
(nome_material, quantidade_estoque, estoque_minimo, unidade_medida, status)
VALUES
('Papelão Ondulado', 5000.00, 1000.00, 'kg', 'Normal'),
('Tinta Amarela', 200.00, 50.00, 'litros', 'Normal'),
('Tinta Vermelha', 180.00, 50.00, 'litros', 'Normal'),
('Tinta Azul', 150.00, 50.00, 'litros', 'Normal'),
('Tinta Preta', 250.00, 50.00, 'litros', 'Normal');


-- LOTES

INSERT INTO LOTE_PRODUCAO
(numero_lote, quantidade, data_inicio, status)
VALUES
('LOT-001', 1000, CURRENT_TIMESTAMP, 'Aberto'),
('LOT-002', 800, CURRENT_TIMESTAMP, 'Aberto');


-- RELACIONAMENTO OF x COR

INSERT INTO OF_COR (id_of, id_cor)
VALUES
(1, 1),
(2, 2),
(2, 4),
(3, 3),
(4, 5),
(5, 9);


-- RELACIONAMENTO OF x MÁQUINA

INSERT INTO OF_MAQUINA
(id_of, id_maquina, ordem_na_fila, status)
VALUES
(1, 1, 1, 'Aguardando'),
(2, 1, 2, 'Aguardando'),
(2, 3, 1, 'Aguardando'),
(3, 1, 3, 'Aguardando'),
(3, 3, 2, 'Aguardando'),
(4, 2, 1, 'Aguardando'),
(4, 4, 1, 'Aguardando'),
(5, 1, 4, 'Aguardando');


-- RELACIONAMENTO OF x LOTE

INSERT INTO OF_LOTE (id_of, id_lote)
VALUES
(1, 1),
(2, 1),
(3, 2);


-- RELACIONAMENTO LOTE x MATÉRIA-PRIMA

INSERT INTO LOTE_MATERIAL
(id_lote, id_material, quantidade_utilizada)
VALUES
(1, 1, 500.00),
(1, 2, 20.00),
(1, 3, 15.00),
(2, 1, 400.00),
(2, 4, 18.00);


-- RELACIONAMENTO CARGA x USUÁRIO

INSERT INTO CARGA_USUARIO
(id_carga, id_usuario)
VALUES
(1, 1),
(2, 1),
(3, 1);


-- MOTIVOS

INSERT INTO MOTIVO
(descricao, tipo)
VALUES
('Urgência de entrega', 'Prioridade'),
('Atraso na produção', 'Produção'),
('Manutenção da máquina', 'Parada');


-- PARADAS

INSERT INTO PARADA_MAQUINA
(data_inicio, data_fim, motivo, observacao)
VALUES
(
    '2026-09-12 08:00:00',
    '2026-09-12 09:00:00',
    'Manutenção',
    'Manutenção preventiva'
);


-- CHECAGEM DE QUALIDADE

INSERT INTO CHECAGEM_QUALIDADE
(data_checagem, resultado, observacao, id_parada)
VALUES
(
    CURRENT_TIMESTAMP,
    'Aprovado',
    'Produto dentro dos padrões de qualidade.',
    1
);


-- USUÁRIO x CHECAGEM

INSERT INTO USUARIO_CHECAGEM
(id_usuario, id_checagem)
VALUES
(1, 1);


-- ALTERAÇÃO DA FILA

INSERT INTO ALTERACAO_FILA
(
    data_alteracao,
    justificativa,
    ordem_anterior,
    nova_ordem,
    id_parada,
    id_material,
    id_motivo
)
VALUES
(
    CURRENT_TIMESTAMP,
    'Urgência de entrega do cliente.',
    3,
    1,
    NULL,
    NULL,
    1
);


-- ============================================================
-- CONSULTAS DE TESTE
-- ============================================================


-- TESTE 1: verificar as máquinas

SELECT *
FROM MAQUINA;


-- TESTE 2: verificar as ordens de fabricação

SELECT *
FROM ORDEM_FABRICACAO;


-- TESTE 3: consultar OFs com suas cargas

SELECT
    OFAB.id_of,
    OFAB.cliente_destino,
    OFAB.cidade,
    OFAB.data_entrega,
    OFAB.peso,
    C.id_carga,
    C.status AS status_carga
FROM ORDEM_FABRICACAO OFAB
LEFT JOIN CARGA C
    ON OFAB.id_carga = C.id_carga;


-- TESTE 4: consultar a fila das máquinas

SELECT
    OM.id_maquina,
    M.nome_maquina,
    OM.id_of,
    OM.ordem_na_fila,
    OM.status
FROM OF_MAQUINA OM
JOIN MAQUINA M
    ON OM.id_maquina = M.id_maquina
ORDER BY
    OM.id_maquina,
    OM.ordem_na_fila;


-- TESTE 5: consultar OFs e suas cores

SELECT
    OFAB.id_of,
    OFAB.cliente_destino,
    C.nome_cor,
    C.ordem_sequenciamento
FROM OF_COR OC
JOIN ORDEM_FABRICACAO OFAB
    ON OC.id_of = OFAB.id_of
JOIN COR C
    ON OC.id_cor = C.id_cor
ORDER BY
    C.ordem_sequenciamento;


-- TESTE 6: verificar cargas e capacidade do veículo

SELECT
    id_carga,
    cidade,
    peso_total,
    capacidade_veiculo,
    status
FROM CARGA
WHERE peso_total <= capacidade_veiculo;


-- TESTE 7: verificar usuários

SELECT
    id_usuario,
    nome,
    login,
    perfil
FROM USUARIO;
